# Generated by Django 4.1.7 on 2023-04-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estoque', '0003_itens_marca_itens_produto_sabor_itens_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itens',
            name='volume',
            field=models.CharField(max_length=30),
        ),
    ]
