# Generated by Django 4.1.7 on 2023-04-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estoque', '0004_alter_itens_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_venda',
            name='data_venda',
            field=models.DateField(auto_now=True),
        ),
    ]
