# Generated by Django 4.1.7 on 2023-05-10 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_estoque', '0008_item_venda_fk_compra_id_alter_item_venda_desconto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itens',
            name='nome',
        ),
    ]
